### ISSUE TITLE
Create Custom Resource Definition and Controller

### ISSUE THREAD

**Issue by kimba74** [kimba74/sandbox-k8s-controller#2]
In order to practice more with `CustomControllers` a new set of `Custom Resource Definitions` (`CRD`) needs to be defined, their corresponding golang types, and client-set need to be generated. Finally these `CRDs` need to be observed and managed by a `Custom Controller`

**Tasks:**
- [x] Create `Custom Resource Definition` YAML files
- [x] Create `apis` package with corresponding go registration and type files
- [x] Generate `client-set`, `informers`, and `listers`
- [ ] Create `Custom Controller`
- [ ] Tie `Cutom Controller` into main project logic
